### ISSUE TITLE
Wont Post The downtime 

### ISSUE THREAD

**Issue by NOXITB** [moonstar-x/discord-downtime-notifier#23] opened 2021-07-23 02:03 UTC
Hi the bot wont post when a bot goes offline can i get some help please

**Comment by AtomicGaming666** [comment] 2021-07-23 02:35
do yours post when th bots come online or just dont it post at all

**Comment by moonstar-x** [comment] 2021-07-23 03:32
I'm gonna close this as it seems to be a duplicate of #22. Please check the solution suggested in that issue.

If you feel like this issue is not a duplicate of the aforementioned one, feel free to re-open it.

**Closed by moonstar-x** 2021-07-23 03:32 UTC
